[project]
name = "uv-testing"
version = "0.1.0"
description = "Working environment for NEISS narrative scoring"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.78.1",
    "pandas>=2.2.3",
    "transformers>=4.51.3",
]
