project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.ipynb"
    - "!ignored.qmd"
    - "!ignored-dir/"

website:
  title: "A Blog for Data Stuff"
  site-url: https://gmcirco.github.io/blog/
  description: "A space for all things data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/gmcirco
      - icon: twitter
        href: https://twitter.com/GioCirco
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
    css: styles.css

editor: visual