"""Keyterms for regex searching through section heads.

Terms are the exact keyword matches in the narrative text
Query is a free-text description of the intended heading
"""

keyterms = {
    "DepressedMood": {
        "Terms": [
            "depressed",
            "depressive symptoms",
            "sad",
            "unhappy",
            "low mood",
            "feeling down",
            "persistent sadness",
            "major depression",
            "melancholy",
            "hopeless",
            "despair",
            "gloomy",
            "emotional distress",
            "tearful",
            "loss of interest",
            "worthlessness",
            "self-loathing",
        ],
        "Query": "Coding rules for DepressedMood",
    },
    "MentalIllnessTreatmentCurrnt": {
        "Terms": [
            "currently in therapy",
            "receiving mental health care",
            "seeing a therapist",
            "psychiatrist",
            "taking psychiatric medication",
            "mental health treatment ongoing",
            "active counseling",
            "outpatient mental health",
            "under psychiatric care",
            "mental health services",
            "on antidepressants",
            "psychological support",
            "inpatient care",
        ],
        "Query": "Coding rules for current mental illness treatment",
    },
    "HistoryMentalIllnessTreatmnt": {
        "Terms": [
            "history of treatment",
            "past therapy",
            "previous counseling",
            "former psychiatric care",
            "was in therapy",
            "had been treated",
            "prior hospitalization",
            "past medication",
            "previous psychiatric diagnosis",
            "treated before for mental illness",
            "formerly medicated",
            "earlier mental health treatment",
            "had received help",
        ],
        "Query": "Coding rules for past mental illness treatment",
    },
    "SuicideAttemptHistory": {
        "Terms": [
            "attempted suicide",
            "tried to kill self",
            "previous suicide attempt",
            "earlier suicide attempt",
            "overdosed intentionally",
            "self-harm with suicidal intent",
            "wrist cutting with intent",
            "tried hanging",
            "history of suicide attempts",
            "prior attempt",
            "deliberate self-injury",
            "had tried before",
        ],
        "Query": "Coding rules for suicide attempt history",
    },
    "SuicideThoughtHistory": {
        "Terms": [
            "suicidal thoughts",
            "considered suicide",
            "suicidal ideation",
            "wanted to die",
            "planned suicide",
            "contemplated suicide",
            "thoughts of ending life",
            "wished to die",
            "suicidal plan",
            "thinking about suicide",
            "preoccupied with death",
            "talked about suicide",
        ],
        "Query": "Coding rules for history of suicidal thoughts",
    },
    "SubstanceAbuseProblem": {
        "Terms": [
            "substance abuse",
            "drug addiction",
            "alcohol addiction",
            "substance use disorder",
            "heavy drinking",
            "opioid abuse",
            "cocaine use",
            "heroin addiction",
            "methamphetamine use",
            "prescription drug misuse",
            "drug dependency",
            "alcohol problem",
            "chronic substance use",
        ],
        "Query": "Coding rules for substance abuse history",
    },
    "DiagnosisAnxiety": {
        "Terms": [
            "anxiety disorder",
            "generalized anxiety",
            "panic disorder",
            "social anxiety",
            "GAD",
            "OCD",
            "obsessive-compulsive disorder",
            "PTSD",
            "post-traumatic stress disorder",
            "phobia",
            "excessive worry",
            "panic attacks",
            "high anxiety",
        ],
        "Query": "Coding rules for anxiety diagnosis",
    },
    "DiagnosisDepressionDysthymia": {
        "Terms": [
            "major depressive disorder",
            "clinical depression",
            "dysthymia",
            "persistent depressive disorder",
            "MDD",
            "chronic depression",
            "treatment-resistant depression",
            "severe depression",
            "recurrent depression",
            "unipolar depression",
        ],
        "Query": "Coding rules for depression and dysthymia diagnosis",
    },
    "DiagnosisBipolar": {
        "Terms": [
            "bipolar disorder",
            "manic depression",
            "bipolar I",
            "bipolar II",
            "cyclothymic disorder",
            "bipolar spectrum disorder",
            "rapid cycling bipolar",
            "manic episodes",
            "hypomania",
            "depressive episodes",
        ],
        "Query": "Coding rules for bipolar disorder diagnosis",
    },
    "DiagnosisAdhd": {
        "Terms": [
            "ADHD",
            "attention deficit disorder",
            "hyperactivity disorder",
            "ADD",
            "inattentive ADHD",
            "impulsive disorder",
            "difficulty focusing",
            "trouble concentrating",
            "attention problems",
        ],
        "Query": "Coding rules for ADHD diagnosis",
    },
    "IntimatePartnerProblem": {
        "Terms": [
            "relationship trouble",
            "marital issues",
            "divorce",
            "breakup",
            "separation",
            "cheating",
            "infidelity",
            "domestic dispute",
            "romantic conflict",
            "estranged spouse",
            "jealousy issues",
        ],
        "Query": "Coding rules for intimate partner problems",
    },
    "FamilyRelationship": {
        "Terms": [
            "family conflict",
            "parental issues",
            "sibling rivalry",
            "estranged family",
            "trouble at home",
            "parental dispute",
            "family argument",
            "domestic issues",
            "strained family ties",
            "child-parent conflict",
            "dysfunctional family",
            "abusive family",
        ],
        "Query": "Coding rules for family relationship issues",
    },
    "SchoolProblem": {
        "Terms": [
            "academic trouble",
            "failing classes",
            "expelled",
            "suspended",
            "bullying",
            "school stress",
            "dropout",
            "bad grades",
            "disciplinary action",
            "trouble with teachers",
            "struggling in school",
        ],
        "Query": "Coding rules for school-related problems",
    },
    "RecentCriminalLegalProblem": {
        "Terms": [
            "legal trouble",
            "arrest",
            "criminal charges",
            "court case",
            "lawsuit",
            "probation",
            "criminal record",
            "legal dispute",
            "police involvement",
            "under investigation",
            "incarceration",
            "law enforcement issues",
        ],
        "Query": "Coding rules for recent criminal and legal problems",
    },
    "SuicideNote": {
        "Terms": [
            "suicide note",
            "final letter",
            "goodbye letter",
            "farewell note",
            "death note",
            "last words",
            "final message",
            "suicide message",
            "note of intent",
        ],
        "Query": "Coding rules for suicide note presence",
    },
    "SuicideIntentDisclosed": {
        "Terms": [
            "talked about suicide",
            "mentioned ending life",
            "discussed suicide",
            "expressed intent to die",
            "spoke about dying",
            "told someone about suicide",
            "revealed suicidal thoughts",
            "admitted suicidal ideation",
        ],
        "Query": "Coding rules for disclosed suicide intent",
    },
    "DisclosedToIntimatePartner": {
        "Terms": [
            "told spouse",
            "told partner",
            "confided in partner",
            "mentioned to girlfriend",
            "mentioned to boyfriend",
            "shared with significant other",
            "told husband",
            "told wife",
        ],
        "Query": "Coding rules for disclosure to intimate partner",
    },
    "DisclosedToOtherFamilyMember": {
        "Terms": [
            "told family",
            "confided in family",
            "mentioned to parent",
            "told sibling",
            "discussed with relatives",
            "told mother",
            "told father",
            "shared with family member",
        ],
        "Query": "Coding rules for disclosure to other family members",
    },
    "DisclosedToFriend": {
        "Terms": [
            "told friend",
            "shared with friend",
            "confided in friend",
            "mentioned to a close friend",
            "talked to best friend",
            "spoke to a peer",
            "discussed with a classmate",
        ],
        "Query": "Coding rules for disclosure to a friend",
    },
}
